### PR TITLE
Show a warning when baker stake exceeds the capital bound

### LINKED ISSUE #283: Provide warning to the baker if the stake will breach capital bound
**Description**
It is possible to stake amount of CCDs that will breach the capital bound without any feedback. All the stake that is over the bound is not counted the usual way when calculating staking rewards.

**Steps to Reproduce**
Stake the amount that is larger of x% of all staked capital.
x is capitalBound parameter and on the Stagenet it is currently set to 25%.

**Expected Result**
Warning that will inform the user about the capital bound.

**Actual Result**
There is no warning.

**Versions**
- Software Version: V 1.4.0-beta.0

### PR DESCRIPTION
**Pull request by shjortConcordium**
## Purpose

Fix #283

## Changes

Display a warning, and the estimated limit, when breaching the capitalBound.
Created a hook for getting capitalBound.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: app/components/PickBakerStakeAmount.tsx [hunk 1]
```diff
@@ -24,6 +36,38 @@ interface Props {
...
+    const rewardStatus = useAsyncMemo(getRewardStatusLatest);
+    const capitalBound = useCapitalBound();
+
+    if (
+        !capitalBound ||
+        !isValidCcdString(stake) ||
+        !rewardStatus ||
+        !isRewardStatusV1(rewardStatus)
+    ) {
+        return { showWarning: false, limitAfterUpdate: 0n };
```
Comment (orhoj) [inline app/components/PickBakerStakeAmount.tsx:55]: You can type this so that `limitAfterUpdate` only has to have a value if `showWarning === true`. Then you only have to check for `showWarning` when using it. Also it improves readability as `limitAfterUpdate` is not really `0` in this case.

**Review by orhoj — CHANGES_REQUESTED** [review]

File: app/components/PickBakerStakeAmount.tsx [hunk 2]
```diff
@@ -24,6 +36,41 @@ interface Props {
...
+        return { showWarning: false };
+    }
+    const newStake = ccdToMicroCcd(stake);
+    const currentStake =
+        accountInfo && isBakerAccount(accountInfo)
+            ? accountInfo.accountBaker.stakedAmount
+            : 0n;
+    const newTotalStake =
+        rewardStatus.totalStakedCapital - currentStake + newStake;
+    const limitAfterUpdate =
```
Comment (orhoj) [inline app/components/PickBakerStakeAmount.tsx:64]: This limit calculation has to also consider any delegated amounts.

Comment (shjortConcordium) [reply app/components/PickBakerStakeAmount.tsx:64]: No, the limit has nothing to do it. I have fixed it, so the delegated amount is taken into consideration when checking if the bound has been violated.

**Review by orhoj — APPROVED** [review]
