### PR TITLE
Fix: Encrypted transfer fail if another is pending

### LINKED ISSUE #45: Encrypted transfer can fail if created while another is pending.
**Bug Description**

If an encrypted transfer is created while another is pending, but sent after the other has been finalized, then it will fail due to invalid proof. 

The same is likely the case for "unshield amount" transfers.

**Steps to Reproduce**

-  Send an encrypted transfer T1.
-  (Quickly) Construct another encrypted transfer and enter the submit page and begin signing T2 on ledger.
-  Wait until T1 has been finalized to complete signing T2 on ledger.

**Expected Result**

T2 is successful. (Or is not allowed to be sent)

**Actual Result**

T2 fails due to invalid proof. 

**Versions**
- 1.1.6
- Linux

### PR DESCRIPTION
**Pull request by shjortConcordium**
## Purpose

Fix #45.

## Changes

When the user tries to create a `shielded transfer` or a `unshield`, they get an error, if they have a pending `shield`/`unshield`/`shielded transfer`.
Now updates ledger component message in `SubmitTransfer.`
Refactored `FinalPage` out of Internal/External Transfer components, to simplify. (and avoid unnecessary calls to node)

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

### CODE REVIEW

File: app/components/Transfers/ensureNoPendingShieldedBalance.tsx [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+import { Account } from '~/utils/types';
+import { hasPendingShieldedBalanceTransfer } from '~/database/TransactionDao';
+import SimpleErrorModal from '~/components/SimpleErrorModal';
+
+export interface WithAccount {
+    account: Account;
+}
+
+/**
+ * Component that injects the next nonce on the given account.
```
Comment (orhoj) [inline app/components/Transfers/ensureNoPendingShieldedBalance.tsx:13]: This is not what this does.

File: app/components/Transfers/ensureNoPendingShieldedBalance.tsx [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        }, [account.address]);
+
+        return (
+            <>
+                <SimpleErrorModal
+                    show={showError}
+                    header="Account has pending transfer impacting shielded balance"
+                    onClick={() => dispatch(routerActions.goBack())}
+                />
+                <Component {...props} />
```
Comment (orhoj) [inline app/components/Transfers/ensureNoPendingShieldedBalance.tsx:38]: Should the component be hidden until we have completed the required check?

File: app/preload/database/transactionsDao.ts [hunk 3]
```diff
@@ -80,6 +81,21 @@ async function hasEncryptedTransactions(
     return Boolean(transaction);
 }
 
+async function hasPendingShieldedBalanceTransfer(fromAddress: string) {
```
Comment (orhoj) [inline app/preload/database/transactionsDao.ts:84]: You need to add some indices to support this query. Currently all it will use is the one on `fromAddress`, and for e.g. a baker account this will be insufficient to make this check effective. A reasonable assumption is that there will always be a limited amount of `Pending` transactions, so in this case you can probably just add an index for TransactionStatus. We will probably need an index on `transactionKind` at some point as well, so consider adding that now too.

File: app/pages/Accounts/SubmitTransfer/SubmitTransfer.tsx [hunk 4]
```diff
@@ -195,14 +199,17 @@ export default function SubmitTransfer({ location }: Props) {
...
+            setMessage
         );
 
         const path = getAccountPath({
             identityIndex: credential.identityNumber,
             accountIndex: credential.credentialNumber,
             signatureIndex,
         });
+
+        setMessage('Please review and sign transaction on device ');
```
Comment (orhoj) [inline app/pages/Accounts/SubmitTransfer/SubmitTransfer.tsx:212]: Remove the extra space at the end.

File: app/components/Transfers/ensureNoPendingShieldedBalance.tsx (hunk 2 above)
Comment (shjortConcordium) [reply app/components/Transfers/ensureNoPendingShieldedBalance.tsx:38]: It is a local check, so it shouldn't be necessary.

File: app/preload/database/transactionsDao.ts (hunk 3 above)
Comment (shjortConcordium) [reply app/preload/database/transactionsDao.ts:84]: I'll add the indices.

File: app/components/Transfers/ensureNoPendingShieldedBalance.tsx [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+                .then(setShowError)
+                .catch(() => {});
+            // eslint-disable-next-line react-hooks/exhaustive-deps
+        }, [account.address]);
+
+        return (
+            <>
+                <SimpleErrorModal
+                    show={showError}
+                    header="Account has pending transfer impacting shielded balance"
```
Comment (orhoj) [inline app/components/Transfers/ensureNoPendingShieldedBalance.tsx:35]: Is it clear that a **shield** transaction is a transfer? Also, I think we should add some body text as it looks weird without. Perhaps it could say:
```
Please wait for any pending shielding transactions or encrypted transfers to finalize.
```

Comment (shjortConcordium) [reply app/components/Transfers/ensureNoPendingShieldedBalance.tsx:35]: I've added it, but changed it to:

```
Please wait for any pending shield amounts, unshield amounts or shielded transfers to finalize.
```

**Review by orhoj — APPROVED** [review]
