### PR TITLE
revise text for delegation views

### LINKED ISSUE #268: Delegation UI text issues
**Bug Description**
The text when delegating to the L-pool is confusing as it refers to an active baker, and there is some extra text that can be deleted.

**Steps to Reproduce**

1. Select an account.
2. Select "Delegate to a pool".

**Expected Result**
The text should say something like:
_This transaction will delegate an amount of CCD to the L-pool. You must choose the amount to delegate._

**Actual Result**
The text currently says:
_This transaction will delegate an amount of CCD to an active baker. You must choose the amount to delegate, if you want to add rewards to the delegated amount._

**Versions**
- Software Version 1.4.0-beta.0

### PR DESCRIPTION
**Pull request by soerenbf**
## Purpose

Fixes #268 

## Changes

- Change text on delegation amount view to take target into account
- Align delegation label on account balance with mobile wallet 

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

### CODE REVIEW

File: app/components/Transfers/configureDelegation/DelegationAmountPage.tsx [hunk 1]
```diff
@@ -184,9 +184,11 @@ export default function DelegationAmountPage({
             <div className="flexChildFill">
                 {existing !== undefined || (
                     <p className="mT0">
-                        This transaction will delegate an amount of CCD to an
-                        active baker. You must choose the amount to delegate, if
-                        you want to add rewards to the delegated amount.
+                        This transaction will delegate an amount of CCD to{' '}
+                        {target === null
+                            ? 'the L-pool'
```
Comment (orhoj) [inline app/components/Transfers/configureDelegation/DelegationAmountPage.tsx:189]: It is no longer called the L-pool, so we have to take that into consideration here.

Comment (soerenbf) [reply app/components/Transfers/configureDelegation/DelegationAmountPage.tsx:189]: Yes, I assume this will be corrected when the document describing the changes needed is in place.. It hasn't been corrected the other places either, has it?

File: app/pages/Accounts/AccountBalanceView/AccountBalanceView.tsx [hunk 2]
```diff
@@ -100,7 +100,7 @@ function PublicInfo({ accountInfo }: PublicInfoProps) {
                             {accountBaker !== undefined &&
                                 `Stake with baker ${accountBaker.bakerId}`}
                             {accountDelegation !== undefined &&
-                                `Delegation with ${getDelegationTargetId(
+                                `Delegating to ${getDelegationTargetId(
```
Comment (orhoj) [inline app/pages/Accounts/AccountBalanceView/AccountBalanceView.tsx:103]:
```suggestion
                                `Delegation to ${getDelegationTargetId(
```

**Review by orhoj — APPROVED** [review]
