### PR TITLE
Include all pages in register baker + update baker pool flows

### LINKED ISSUE #242: We inform the user that commission rates are changeable which is incorrect
**Bug Description**
Commission rates are fixed and the text in pool settings is written as its configurable.

**Steps to Reproduce**
Try to add baker through DW.
Pool settings are presented as changeable.

**Expected Result**
Text should be adjusted with the non configurable commission rates.

**Actual Result**
image

**Versions**
- Software Version: DW V 1.4.0-alpha.0

### LINKED ISSUE #250: Remove baker - CCDs are not released right after the cooldown period but on the next payday
**Bug Description**
After removing baker, DW provides exact estimation on when will the CCDs be released and back on users disposal. However this estimation doesn't hold anymore since the stake is not released just after the cooldown period  but on the next payday after the cooldown period.
In my example on Stagenet I had to wait another 10 minutes from the estimated time (payday is every 11 min), this will be much longer waiting period on Mainnnet.

**Steps to Reproduce**
Register a baker, receive a reward.
Stop baker.
Observe estimated time of cooldown.
Verify that CCDs are released as estimated.

**Expected Result**
Inform the user that CCDs should be released on a payday as estimated. 
CCDs are released as estimated.

**Actual Result**
CCDs are released on a payday but we inform the user that CCDs will be released right after the cooldown.
**Versions**
- Software Version: V 1.4.0-alpha.0

### PR DESCRIPTION
**Pull request by soerenbf**
## Purpose

As described in title. Also includes a number of small improvements to the delegation/baker flows

Closes #242, closes #250

## Changes

- Remove conditionality for pages in respective flows.
- Separate add/update delegation flows into different routes

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

### CODE REVIEW

File: app/utils/timeHelpers.ts [hunk 1]
```diff
@@ -267,29 +274,71 @@ export const isDateEqual = (
...
 };
 
+/**
+ * Gets time of the payday after a given time.
+ *
+ * @param time the time for which the succeeding payday is returned
+ * @param nextPayday the next payday in relation to current time
+ * @param rewardPeriodLengthMS the length of a payday in milliseconds
+ */
+export const getSucceedingPayday = (
```
Comment (shjortConcordium) [inline app/utils/timeHelpers.ts:284]: what is this :thinking:

Comment (shjortConcordium) [reply app/utils/timeHelpers.ts:284]: nvm, I think I get it. You are finding the payday after the effective time by recursive, linear search?

Comment (soerenbf) [reply app/utils/timeHelpers.ts:284]: Yes! 🥇

**Review by shjortConcordium — APPROVED** [review]
