### PR TITLE
Set default account description modal + transaction list element border bug

### LINKED ISSUE #91: Add description for first time setting default account
**Description**

When setting a default account for the first time, it would be nice with a modal describing the action, like we have when the user sets a new default account, overriding the old one.

### PR DESCRIPTION
**Pull request by soerenbf**
## Purpose

Shows a modal first time a default account is set, describing the action at what it implies. Also fixes a small style bug on transaction list elements introduced in #60 

## Changes

- Show prompt modal when setting default account first time
- Hide top border for first transaction list element in list group.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

Closes #91

### CODE REVIEW

**Comment by shjortConcordium** [comment]
The transaction list element border bug is now present on the top, in the infinite list.

**Comment by soerenbf** [comment]
> The transaction list element border bug is now present on the top, in the infinite list.

😢 

Should be fixed now!

**Review by shjortConcordium — APPROVED** [review]

File: app/pages/Accounts/TransactionList/InfiniteTransactionList.tsx [hunk 1]
```diff
@@ -140,7 +140,14 @@ export default function InfiniteTransactionList({
...
                                     if (isHeader(item)) {
-                                        return null; // Handled in "innerElementType"
+                                        return (
+                                            <span
+                                                className={
+                                                    styles.transactionGroupHeaderPlaceholder
+                                                }
+                                                style={style}
+                                            />
+                                        ); // Handled in "innerElementType"
```
Comment (shjortConcordium) [inline app/pages/Accounts/TransactionList/InfiniteTransactionList.tsx:150]: Does this count as handling?
